### ISSUE TITLE
Missing GlobalCEFApp.FrameworkDirPath

### ISSUE THREAD

**Issue by yeschoto** [salvadordf/OldCEF4Delphi#1]
Why missing property GlobalCEFApp.FrameworkDirPath ? 
How can I set the libs path in OldCEF4Delphi?
In CEF4Delphi can be: 
    GlobalCEFApp.FrameworkDirPath := ExtractFilePath(ParamStr(0)) + 'lib';
    GlobalCEFApp.ResourcesDirPath := ExtractFilePath(ParamStr(0)) + 'lib';
    GlobalCEFApp.LocalesDirPath   := ExtractFilePath(ParamStr(0)) + 'lib\locales';

**Comment by salvadordf** [comment]
**GlobalCEFApp.FrameworkDirPath** exposes **framework_dir_path** in a CEF3 struct called **cef_settings_t**.

The problem is that framework_dir_path was added to CEF in a later branch. The 2623 branch which OldCEF4Delphi uses can't set a framework path.

I haven't tried to move all the binaries to another directory using OldCEF4Delphi.

**Comment by 156704883** [comment]
I have tried to move all the binaries to another directory using OldCEF4Delphi. Can work

**Comment by t8soft** [comment]
> I have tried to move all the binaries to another directory using OldCEF4Delphi. Can work

How did you achieve it? What changed?？？

**Comment by reghtml** [comment]
> binaries

我也遇到了同样的问题，请教一下

**Comment by reghtml** [comment]
> binaries

I have the same problem. Please consult me
