### ISSUE TITLE
delphi XE10.3 + TFMXChromium cannot run on XP

### ISSUE THREAD

**Issue by Y-A-K-E** [salvadordf/OldCEF4Delphi#10]
hi,
I use your SimpleFMXBrowser . compiled 32-bit program file can work in the system after Win7. But the XP system abnormal exit. TChromium (OldCEF4Delphi_FMX) can work on the XP.

The original DELPHI 10.2 + TFMXChromium can work on the XP .

I uninstalled the original packages, re-cloned the code you submitted four days ago, and reinstalled OldCEF4Delphi_FMX. (I did not install OldCEF4Delphi)

 cannot work on the XP system.

**Comment by salvadordf** [comment]
I only have Windows 7 and 10 in two PCs. I'll have to ask for some favors to test this issue.

**Comment by salvadordf** [comment]
The last Delphi version that supported Windows XP as a development platform was Delphi XE2 : 
http://docwiki.embarcadero.com/RADStudio/XE2/en/Installation_Notes_for_XE2

Delphi XE5 was the last version that could be safely used to create Windows XP applications : 
https://stackoverflow.com/questions/30505058/why-can-applications-developed-with-embarcadero-xe6-or-higher-not-target-xp

If you build your application in a newer Delphi version you may have unexpected problems like this one when you run it in Windows XP because Embarcadero no longer tests those applications in that operating system.

The best solution would be to build your application with Delphi XE5. FireMonkey has changed a lot since then and you might have to adapt the FMX code in OldCEF4Delphi to Delphi XE5. 

I'm sorry, but I'm afraid I can't help you because I don't have a Delphi XE5 license.
