### ISSUE TITLE
PrintToPDF when setting custom Width & Height

### ISSUE THREAD

**Issue by hafedh-trimeche** [salvadordf/OldCEF4Delphi#14]
Hello,

Please note that when using this code:
```
procedure TForm1.chrmosrPdfPrintFinished(Sender:TObject;aResultOK:Boolean);
begin
  PrintPDFFinished := True;
  PrintPDFOK       := aResultOK;
end;

procedure TForm1.SnapshotBtnClick(Sender: TObject);
var
  TempSettings : TCefPdfPrintSettings;
  TempCallback : ICefPdfPrintCallback;
begin
  PrintPDFFinished := False;
  PrintPDFOK       := False;
  TempSettings     := default(TCefPdfPrintSettings);
  with TempSettings do
  begin
    header_footer_title := CefString(DocumentTitle);
    page_width          := round(scrollWidth*25.4/Screen.DefaultPixelsPerInch);
    page_height         := round(scrollHeight*25.4/Screen.DefaultPixelsPerInch);
    margin_type         := PDF_PRINT_MARGIN_NONE;
    backgrounds_enabled := 1;
  end;
  TempCallback := TCefCustomPDFPrintCallBack.Create(chrmosr);
  chrmosr.Browser.Host.PrintToPdf('c:\sb.pdf',@TempSettings,TempCallback);
  while (not PrintPDFFinished) do
  begin
    Sleep(1);
    Application.ProcessMessages;
  end;
end;
```
and after setting **scrollWidth** to **794** and **scrollHeight** to **1533** the **OnPDFPrintFinished** never fired. However, setting Width (**page_width**) and Height (**page_height**) to **0** worked well and the generated PDF is split into 2 pages.

How to configure **TCefPdfPrintSettings** to let PDF fit into single page?

Best regards.

**Comment by salvadordf** [comment]
Use the code in the MiniBrowser demo and add your custom page size like this : 

procedure TMiniBrowserFrm.PrintinPDF1Click(Sender: TObject);
begin
  SaveDialog1.DefaultExt := 'pdf';
  SaveDialog1.Filter     := 'PDF files (*.pdf)|*.PDF';

  if SaveDialog1.Execute and (length(SaveDialog1.FileName) > 0) then
    begin
      Chromium1.PDFPrintOptions.page_width := 794;
      Chromium1.PDFPrintOptions.page_height := 1533;
      Chromium1.PDFPrintOptions.margin_type := PDF_PRINT_MARGIN_NONE;
      Chromium1.PDFPrintOptions.backgrounds_enabled := True;
      Chromium1.PrintToPDF(SaveDialog1.FileName, Chromium1.DocumentURL, Chromium1.DocumentURL);
    end;
end;

I just tested this code and the Chromium1PdfPrintFinished event was triggered correctly.

Please, consider using the latest CEF4Delphi version if possible because OldCEF4Delphi uses a very old version of CEF with internal issues that were fixed in more recent versions.
